#!/bin/sh
#
# Usage: extract <file>
# Description: extracts archived files / mounts disk images
# Note: .dmg/hdiutil is macOS-specific.
#
# credit: http://nparikh.org/notes/zshrc.txt

extract () {
    # Check if the file exists
    if [ -f "$1" ]; then
        case "$1" in
            *.tar.bz2)  tar -jxvf "$1"                        ;;
            *.tar.gz)   tar -zxvf "$1"                        ;;
            *.bz2)      bunzip2 "$1"                          ;;
            *.dmg)      if command -v hdiutil > /dev/null; then
                            hdiutil mount "$1"
                        else
                            echo "hdiutil not found. This command is macOS-specific."
                        fi
                        ;;
            *.gz)       gunzip "$1"                           ;;
            *.tar)      tar -xvf "$1"                         ;;
            *.tbz2)     tar -jxvf "$1"                        ;;
            *.tgz)      tar -zxvf "$1"                        ;;
            *.zip)      unzip "$1"                            ;;
            *.ZIP)      unzip "$1"                            ;;
            *.pax)      if command -v pax > /dev/null; then
                            pax -r < "$1"
                        else
                            echo "pax not found."
                        fi
                        ;;
            *.pax.Z)    if command -v uncompress > /dev/null && command -v pax > /dev/null; then
                            uncompress --stdout "$1" | pax -r
                        else
                            echo "uncompress or pax not found."
                        fi
                        ;;
            *.rar)      if command -v unrar > /dev/null; then
                            unrar x "$1"
                        else
                            echo "unrar not found."
                        fi
                        ;;
            *.Z)        uncompress "$1"                       ;;
            *)          echo "'$1' cannot be extracted/mounted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
