-- return {
--   'zbirenbaum/copilot.lua',
--   cmd = 'Copilot',
--   build = ':Copilot auth',
--   event = 'BufReadPost',
--   opts = {
--     panel = {
--       enabled = false,
--       auto_refresh = false,
--       keymap = {
--         jump_prev = '[[',
--         jump_next = ']]',
--         accept = '<CR>',
--         refresh = 'gr',
--         open = '<M-CR>',
--       },
--       layout = {
--         position = 'right', -- | top | left | right | horizontal | vertical
--         ratio = 0.4,
--       },
--     },
--     suggestion = {
--       enabled = false,
--       auto_trigger = false,
--       keymap = {
--         accept = '<M-l>',
--         next = '<M-]>',
--         prev = '<M-[>',
--         dismiss = '<C-]>',
--       },
--     },
--   },
-- }
