-- return {
--   'CopilotC-Nvim/CopilotChat.nvim',
--   branch = 'main',
--   cmd = 'CopilotChat',
--   opts = function()
--     local user = vim.env.USER or 'User'
--     user = user:sub(1, 1):upper() .. user:sub(2)
--     return {
--       auto_insert_mode = true,
--       question_header = '  ' .. user .. ' ',
--       answer_header = '  Copilot ',
--       window = {
--         width = 0.4,
--       },
--       model = 'claude-3.7-sonnet',
--       chat_autocomplete = true,
--       prompts = {
--         Docs = {
--           prompt = 'Generate comprehensive documentation comments for the following code, including a summary, parameter descriptions, return value, and any important notes or examples. Use clear and concise language suitable for developers.',
--         },
--         Test = {
--           prompt = 'Write unit tests for my code. Include tests for typical use cases, edge cases, and potential failure scenarios. Ensure good coverage and clear assertions.',
--         },
--         GolangMicroService = {
--           system_prompt = 'Act as an experienced Go developer working on a microservices-based application that uses gRPC and Protocol Buffers for inter-service communication. Generate idiomatic Go code that follows best practices for gRPC services, server and client implementation, and proper context and error handling. Structure the code to be modular, testable, and scalable. Use environment variables for config, and include helpful comments and logging where appropriate.'
--             .. require('CopilotChat.config.prompts').COPILOT_BASE.system_prompt,
--         },
--       },
--     }
--   end,
--   keys = {
--     { '<c-s>', '<CR>', ft = 'copilot-chat', desc = 'Submit Prompt', remap = true },
--     { '<leader>a', '', desc = '+ai', mode = { 'n', 'v' } },
--     {
--       '<leader>aa',
--       function()
--         return require('CopilotChat').toggle()
--       end,
--       desc = 'Toggle (CopilotChat)',
--       mode = { 'n', 'v' },
--     },
--     {
--       '<leader>ax',
--       function()
--         return require('CopilotChat').reset()
--       end,
--       desc = 'Clear (CopilotChat)',
--       mode = { 'n', 'v' },
--     },
--     {
--       '<leader>aq',
--       function()
--         vim.ui.input({
--           prompt = 'Quick Chat: ',
--         }, function(input)
--           if input ~= '' then
--             require('CopilotChat').ask(input)
--           end
--         end)
--       end,
--       desc = 'Quick Chat (CopilotChat)',
--       mode = { 'n', 'v' },
--     },
--     {
--       '<leader>ap',
--       function()
--         require('CopilotChat').select_prompt()
--       end,
--       desc = 'Prompt Actions (CopilotChat)',
--       mode = { 'n', 'v' },
--     },
--   },
--   config = function(_, opts)
--     local chat = require 'CopilotChat'
--
--     vim.api.nvim_create_autocmd('BufEnter', {
--       pattern = 'copilot-chat',
--       callback = function()
--         vim.opt_local.relativenumber = false
--         vim.opt_local.number = false
--       end,
--     })
--
--     chat.setup(opts)
--   end,
-- }
